### ISSUE TITLE
Autoparagraphing ignores empty elements

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-paragraph#11]
Currently, loading a single image or `foo<img>bar` into the editor will not trigger the autoparagraphing of that image (if images were treated as inline elements).

This is a conscious decision made in order to simplify #3, because I had enough fun implementing the behaviour for the text. Also, https://github.com/ckeditor/ckeditor5-paragraph/issues/10 is more actually more important than this issue, so I'd actually spend time fixing that one.

What makes this particular issue even less important is that right now we have only one such element – image, and it's block oriented. Plus, it will have to have its own converter for inline images: https://github.com/ckeditor/ckeditor5-image/issues/8.

**Comment by scofalik** [comment]
I tried to fix it in naive way, by allowing `autoparagraphText` converter to be fired also for elements, but this fails because first default to-document-fragment converter is fired.

**Comment by scofalik** [comment]
> I tried to fix it in naive way, by allowing `autoparagraphText` converter to be fired also for elements

Okay, this idea is bad because we should also check whether given element is allowed in paragraph (current `autoparagraphText` silently assumes that bare text is always allowed in paragraph). To check this, we need to know to which element current element will be converted because we need that info for `schema.check()`. ATM we are unable to get it because we don't know to what element `data.input` is supposed to be converted.
